
export const GET_BLOGS = 'GET_BLOGS'
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'
export const GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE'

export const GET_BLOGS_CATEGORIES = 'GET_BLOGS_CATEGORIES'
export const GET_BLOGS_CATEGORIES_SUCCESS = 'GET_BLOGS_CATEGORIES_SUCCESS'
export const GET_BLOGS_CATEGORIES_FAILURE = 'GET_BLOGS_CATEGORIES_FAILURE'
