// Account settings
export const DSHBRD__PROFILE_PICTURE_UPLOAD_MODAL_TOGGLE = 'DSHBRD__PROFILE_PICTURE_UPLOAD_MODAL_TOGGLE'

export const DSHBRD__UPLOAD_NEW_PROFILE_PICTURE_SUCCESS = 'DSHBRD__UPLOAD_NEW_PROFILE_PICTURE_SUCCESS'
export const DSHBRD__UPLOAD_NEW_PROFILE_PICTURE_FAILED = 'DSHBRD__UPLOAD_NEW_PROFILE_PICTURE_FAILED'

export const DSHBRD__SET_NEW_PROFILE_PICTURE = 'DSHBRD__SET_NEW_PROFILE_PICTURE'

export const DSHBRD__REMOVE_PROFILE_PICTURE = 'DSHBRD__REMOVE_PROFILE_PICTURE'
export const DSHBRD__REMOVE_PROFILE_PICTURE_SUCCESS = 'DSHBRD__REMOVE_PROFILE_PICTURE_SUCCESS'
export const DSHBRD__REMOVE_PROFILE_PICTURE_FAILED = 'DSHBRD__REMOVE_PROFILE_PICTURE_FAILED'

export const DSHBRD_UPDATE_PROFILE = 'DSHBRD_UPDATE_PROFILE'
export const DSHBRD_UPDATE_PROFILE_SUCCESS = 'DSHBRD_UPDATE_PROFILE_SUCCESS'
export const DSHBRD_UPDATE_PROFILE_FAILED = 'DSHBRD_UPDATE_PROFILE_FAILED'

export const DSHBRD_GET_PROFILE_DETAILS = 'DSHBRD_GET_PROFILE_DETAILS'
export const DSHBRD_GET_PROFILE_DETAILS_SUCCESS = 'DSHBRD_GET_PROFILE_DETAILS_SUCCESS'
export const DSHBRD_GET_PROFILE_DETAILS_FAILED = 'DSHBRD_GET_PROFILE_DETAILS_FAILED'

export const TOGGLE_MODALS = 'TOGGLE_MODALS'

export const DSHBRD__CHANGE_PASSWORD = 'DSHBRD__CHANGE_PASSWORD'
export const DSHBRD__CHANGE_PASSWORD_SUCCESS = 'DSHBRD__CHANGE_PASSWORD_SUCCESS'
export const DSHBRD__CHANGE_PASSWORD_FAILED = 'DSHBRD__CHANGE_PASSWORD_FAILED'

// My Alerts
export const DSHBRD__GET_SUBSCRIBED_ALERTS = 'DSHBRD__GET_SUBSCRIBED_ALERTS'
export const DSHBRD__GET_SUBSCRIBED_ALERTS_SUCCESS = 'DSHBRD__GET_SUBSCRIBED_ALERTS_SUCCESS'
export const DSHBRD__GET_SUBSCRIBED_ALERTS_FAILED = 'DSHBRD__GET_SUBSCRIBED_ALERTS_FAILED'

export const DSHBRD__CANCEL_SUBSCRIBED_ALERTS = 'DSHBRD__CANCEL_SUBSCRIBED_ALERTS'
export const DSHBRD__CANCEL_SUBSCRIBED_ALERTS_SUCCESS = 'DSHBRD__CANCEL_SUBSCRIBED_ALERTS_SUCCESS'
export const DSHBRD__CANCEL_SUBSCRIBED_ALERTS_FAILED = 'DSHBRD__CANCEL_SUBSCRIBED_ALERTS_FAILED'

export const EDIT_ALERT = 'EDIT_ALERT'
export const EDIT_ALERT_SUCCESS = 'EDIT_ALERT_SUCCESS'
export const EDIT_ALERT_FAILED = 'EDIT_ALERT_FAILED'

export const SET_SOCIAL_USER_PASSWORD = 'SET_SOCIAL_USER_PASSWORD'
export const SET_SOCIAL_USER_PASSWORD_SUCCESS = 'SET_SOCIAL_USER_PASSWORD_SUCCESS'
export const SET_SOCIAL_USER_PASSWORD_FAILED = 'SET_SOCIAL_USER_PASSWORD_FAILED'

export const ADD_ALTERNATE_EMAIL = 'ADD_ALTERNATE_EMAIL'
export const ADD_ALTERNATE_EMAIL_SUCCESS = 'ADD_ALTERNATE_EMAIL_SUCCESS'
export const ADD_ALTERNATE_EMAIL_FAILED = 'ADD_ALTERNATE_EMAIL_FAILED'

export const EDIT_ALTERNATE_EMAIL = 'EDIT_ALTERNATE_EMAIL'
export const EDIT_ALTERNATE_EMAIL_SUCCESS = 'EDIT_ALTERNATE_EMAIL_SUCCESS'
export const EDIT_ALTERNATE_EMAIL_FAILED = 'EDIT_ALTERNATE_EMAIL_FAILED'

export const DELETE_ALTERNATE_EMAIL = 'DELETE_ALTERNATE_EMAIL'
export const DELETE_ALTERNATE_EMAIL_SUCCESS = 'DELETE_ALTERNATE_EMAIL_SUCCESS'
export const DELETE_ALTERNATE_EMAIL_FAILED = 'DELETE_ALTERNATE_EMAIL_FAILED'

export const GET_PRE_SIGNED_URL = 'GET_PRE_SIGNED_URL'
export const GET_PRE_SIGNED_URL_SUCCESS = 'GET_PRE_SIGNED_URL_SUCCESS'
export const GET_PRE_SIGNED_URL_FAILED = 'GET_PRE_SIGNED_URL_FAILED'

export const VERIFY_SMS_OTP = 'VERIFY_SMS_OTP'
export const VERIFY_SMS_OTP_SUCCESS = 'VERIFY_SMS_OTP_SUCCESS'
export const VERIFY_SMS_OTP_FAILED = 'VERIFY_SMS_OTP_FAILED'

export const RESEND_SMS_OTP = 'RESEND_SMS_OTP'
export const RESEND_SMS_OTP_SUCCESS = 'RESEND_SMS_OTP_SUCCESS'
export const RESEND_SMS_OTP_FAILED = 'RESEND_SMS_OTP_FAILED'

export const TOGGLE_SMS_NOTIFICATION = 'TOGGLE_SMS_NOTIFICATION'
export const TOGGLE_SMS_NOTIFICATION_SUCCESS = 'TOGGLE_SMS_NOTIFICATION_SUCCESS'
export const TOGGLE_SMS_NOTIFICATION_FAILED = 'TOGGLE_SMS_NOTIFICATION_FAILED'

export const SET_EMAIL_PRIMARY = 'SET_EMAIL_PRIMARY'
export const SET_EMAIL_PRIMARY_SUCCESS = 'SET_EMAIL_PRIMARY_SUCCESS'
export const SET_EMAIL_PRIMARY_FAILED = 'SET_EMAIL_PRIMARY_FAILED'

export const RESEND_VERIFICATION_EMAIL = 'RESEND_VERIFICATION_EMAIL'
export const RESEND_VERIFICATION_EMAIL_SUCCESS = 'RESEND_VERIFICATION_EMAIL_SUCCESS'
export const RESEND_VERIFICATION_EMAIL_FAILED = 'RESEND_VERIFICATION_EMAIL_FAILED'

export const TOGGLE_EMAILS_NOTIFICATION = 'TOGGLE_EMAIL_NOTIFICATION'
export const TOGGLE_EMAILS_NOTIFICATION_SUCCESS = 'TOGGLE_EMAIL_NOTIFICATION_SUCCESS'
export const TOGGLE_EMAILS_NOTIFICATION_FAILED = 'TOGGLE_EMAIL_NOTIFICATION_FAILED'

export const DELETE_PHONE_NUMBER = 'DELETE_PHONE_NUMBER'
export const DELETE_PHONE_NUMBER_SUCCESS = 'DELETE_PHONE_NUMBER_SUCCESS'
export const DELETE_PHONE_NUMBER_FAILED = 'DELETE_PHONE_NUMBER_FAILED'

export const CANCEL_DOWNGRADE_SUBSCRIPTION = 'CANCEL_DOWNGRADE_SUBSCRIPTION'
export const CANCEL_DOWNGRADE_SUBSCRIPTION_SUCCESS = 'CANCEL_DOWNGRADE_SUBSCRIPTION_SUCCESS'
export const CANCEL_DOWNGRADE_SUBSCRIPTION_FAILURE = 'CANCEL_DOWNGRADE_SUBSCRIPTION_FAILURE'
