export const GET_FLIGHT_AVAILABILITY = 'GET_FLIGHT_AVAILABILITY'
export const GET_FLIGHT_AVAILABILITY_SUCCESS = 'GET_FLIGHT_AVAILABILITY_SUCCESS'
export const GET_FLIGHT_AVAILABILITY_FAILURE = 'GET_FLIGHT_AVAILABILITY_FAILURE'

export const CREATE_USER_ACTION_AUDIT = 'CREATE_USER_ACTION_AUDIT'
export const CREATE_USER_ACTION_AUDIT_SUCCESS = 'CREATE_USER_ACTION_AUDIT_SUCCESS'
export const CREATE_USER_ACTION_AUDIT_FAILURE = 'CREATE_USER_ACTION_AUDIT_FAILURE'

export const GET_ALERT_AVAILABILITY = 'GET_ALERT_AVAILABILITY'
export const GET_ALERT_AVAILABILITY_SUCCESS = 'GET_ALERT_AVAILABILITY_SUCCESS'
export const GET_ALERT_AVAILABILITY_FAILURE = 'GET_ALERT_AVAILABILITY_FAILURE'
