
export const UPDATE_REDUCER_STATE = 'UPDATE_REDUCER_STATE'

export const GET_TESTIMONIAL = 'GET_TESTIMONIAL'
export const GET_TESTIMONIAL_SUCCESS = 'GET_TESTIMONIAL_SUCCESS'
export const GET_TESTIMONIAL_FAILED = 'GET_TESTIMONIAL_FAILED'

export const GET_PAGE_CONTENT = 'GET_PAGE_CONTENT'
export const GET_PAGE_CONTENT_SUCCESS = 'GET_PAGE_CONTENT_SUCCESS'
export const GET_PAGE_CONTENT_FAILED = 'GET_PAGE_CONTENT_FAILED'

export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const UPDATE_USER_NAME_SUCCESS = 'UPDATE_USER_NAME_SUCCESS'
export const UPDATE_USER_NAME_FAILED = 'UPDATE_USER_NAME_FAILED'
