export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS'
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE'

export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'

export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST'
export const FACEBOOK_LOGIN_REQUEST_SUCCESS = 'FACEBOOK_LOGIN_REQUEST_SUCCESS'
export const FACEBOOK_LOGIN_REQUEST_FAILURE = 'FACEBOOK_LOGIN_REQUEST_FAILURE'

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_REQUEST_SUCCESS = 'GOOGLE_LOGIN_REQUEST_SUCCESS'
export const GOOGLE_LOGIN_REQUEST_FAILURE = 'GOOGLE_LOGIN_REQUEST_FAILURE'

export const APPLE_LOGIN_REQUEST = 'APPLE_LOGIN_REQUEST'
export const APPLE_LOGIN_REQUEST_SUCCESS = 'APPLE_LOGIN_REQUEST_SUCCESS'
export const APPLE_LOGIN_REQUEST_FAILURE = 'APPLE_LOGIN_REQUEST_FAILURE'

export const GET_PRE_SIGNED_URL_AUTH = 'GET_PRE_SIGNED_URL_AUTH'
export const GET_PRE_SIGNED_URL_AUTH_SUCCESS = 'GET_PRE_SIGNED_URL_AUTH_SUCCESS'
