
export const GET_FAQ = 'GET_FAQ'
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS'
export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE'

export const GET_FAQ_CATEGORIES = 'GET_FAQ_CATEGORIES'
export const GET_FAQ_CATEGORIES_SUCCESS = 'GET_FAQ_CATEGORIES_SUCCESS'
export const GET_FAQ_CATEGORIES_FAILURE = 'GET_FAQ_CATEGORIES_FAILURE'
