export const GET_AIRLINE_LIST = 'GET_AIRLINE_LIST'
export const GET_AIRLINE_LIST_SUCCESS = 'GET_AIRLINE_LIST_SUCCESS'
export const GET_AIRLINE_LIST_FAILURE = 'GET_AIRLINE_LIST_FAILURE'

export const GET_SEARCHED_LOCATION = 'GET_SEARCHED_LOCATION'
export const SET_SEARCHED_LOCATION = 'SET_SEARCHED_LOCATION'

export const SEND_ME_ALERT = 'SEND_ME_ALERT'
export const SEND_ME_ALERT_SUCCESS = 'SEND_ME_ALERT_SUCCESS'
export const SEND_ME_ALERT_FAILURE = 'SEND_ME_ALERT_FAILURE'

export const RESET_SELECTED_ALERT_DATES = 'RESET_SELECTED_ALERT_DATES'

export const TSB__UPDATE_TICKETS_SEARCH_BOX = 'TSB__UPDATE_TICKETS_SEARCH_BOX'
export const TSB__CHANGE_TICKET_CLASS = 'TSB__CHANGE_TICKET_CLASS'

export const TSB__UPDATE_DONOT_KNOW_OBJ = 'TSB__UPDATE_DONOT_KNOW_OBJ'

export const GET_SOU_DES_LOCATIONS = 'GET_SOU_DES_LOCATIONS'
export const GET_SOU_DES_LOCATIONS_SUCCESS = 'GET_SOU_DES_LOCATIONS_SUCCESS'
export const GET_SOU_DES_LOCATIONS_FAILURE = 'GET_SOU_DES_LOCATIONS_FAILURE'

export const UPDATE_TOGGAL_CLASS_STATE = 'UPDATE_TOGGAL_CLASS_STATE'

export const GET_SOU_DES_POSSIBLE_ROUTES = 'GET_SOU_DES_POSSIBLE_ROUTES'
export const GET_SOU_DES_POSSIBLE_ROUTES_SUCCESS = 'GET_SOU_DES_POSSIBLE_ROUTES_SUCCESS'
export const GET_SOU_DES_POSSIBLE_ROUTES_FAILURE = 'GET_SOU_DES_POSSIBLE_ROUTES_FAILURE'

export const GET_USER_NEAREST_AIRPORT = 'GET_USER_NEAREST_AIRPORT'
export const GET_USER_NEAREST_AIRPORT_SUCCESS = 'GET_USER_NEAREST_AIRPORT_SUCCESS'
export const GET_USER_NEAREST_AIRPORT_FAILED = 'GET_USER_NEAREST_AIRPORT_FAILED'
