export const GET_PRICING_PLANS = 'GET_PRICING_PLANS'
export const GET_PRICING_PLANS_SUCCESS = 'GET_PRICING_PLANS_SUCCESS'
export const GET_PRICING_PLANS_FAILURE = 'GET_PRICING_PLANS_FAILURE'

// cancel elite membership constamts
export const CANCEL_ELITE_MEMBERSHIP = 'CANCEL_ELITE_MEMBERSHIP'
export const CANCEL_ELITE_MEMBERSHIP_SUCCESS = 'CANCEL_ELITE_MEMBERSHIP_SUCCESS'
export const CANCEL_ELITE_MEMBERSHIP_FAILURE = 'CANCEL_ELITE_MEMBERSHIP_FAILURE'

export const ADD_EMAIL = 'ADD_EMAIL'
export const ADD_EMAIL_SUCCESS = 'ADD_EMAIL_SUCCESS'
export const ADD_EMAIL_FAILED = 'ADD_EMAIL_FAILED'
