const env = {
  CMS_BASE_URL: process.env.REACT_APP_CMS_APP_URL,
  BASE_URL_NODE: process.env.REACT_APP_BASE_URL_NODE,
  REDIRECT_ON_RUBY: process.env.REACT_APP_REDIRECT_ON_RUBY,
  REACT_APP_BASE_URL_RUBY: process.env.REACT_APP_BASE_URL_RUBY,
  AUTHORIZATION_KEY: process.env.REACT_APP_AUTHORIZATION_KEY,
  FACEBOOK_APP_IDE: process.env.REACT_APP_FACEBOOK_APP_ID,
  GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
  MAP_BOX_GL_TOKEN: process.env.REACT_APP_MAP_BOX_GL_TOKEN,
  REACT_APP_MAPTILER_ACCESS_TOKEN: process.env.REACT_APP_MAPTILER_ACCESS_TOKEN,
  REACT_APP_MAILBOX_API_ACCESSKEY: process.env.REACT_APP_MAILBOX_API_ACCESSKEY,
  REACT_APP_APPLE_CLIENTID: process.env.REACT_APP_APPLE_CLIENTID,
  REACT_APP_URL: process.env.REACT_APP_URL
}

export default env
