export const DSHBRD__TOGGLE_SIDEBAR = 'DSHBRD__TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const ADD_FINGERPRINT_SCRAPPER_DATA = 'ADD_FINGERPRINT_SCRAPPER_DATA'
export const ADD_FINGERPRINT_SCRAPPER_DATA_SUCCESS = 'ADD_FINGERPRINT_SCRAPPER_DATA_SUCCESS'
export const ADD_FINGERPRINT_SCRAPPER_DATA_FAILURE = 'ADD_FINGERPRINT_SCRAPPER_DATA_FAILURE'