// cookie policy page
export const WHAT_IS_COOKIE = 'A cookie is a small text file that is downloaded onto ‘terminal equipment’ (e g a computer or smartphone) when the user accesses a website. It allows the website to recognise that user’s device and store some information about the user’s preferences or past actions.'
export const COOKIE_USE_1 = 'When you use our website, you may receive cookies from us and/or third parties (acting on our behalf) that collect information. We use cookies to ensure that we give you a high-quality experience. We also use cookies to show you advertising that is relevant to you.'
export const COOKIE_USE_2 = 'We use cookies when they are essential to deliver our services, to authenticate users, to store your preferences, to improve your experience through analytics and optimisation and to deliver personalised ads.'
export const COOKIE_USE_3 = 'However, if you prefer, you can change your cookie settings. Some browsers have options that allow the visitor to control whether the browser will accept, reject, or notify the visitor each time a cookie is sent. You may elect to reject cookies by adjusting your settings, but doing so will limit the range of features available to you on our website.'
export const ESSENTIAL_COOKIE = 'These cookies enable you to use our services. These cookies are essential to enable you to browse our services and use certain features. Disabling them may prevent you from using certain parts of the website. These cookies also help keep our website safe and secure.'
export const PREFERENCE_COOKIE = 'These cookies store information such as your login data and website preferences. Without these cookies, our website may not be able to remember certain choices you’ve previously made or personalize your browsing experience by providing you with relevant information. These cookies can also be used to recognize your device so that you do not have to provide the same information more than once.'
export const PERFORMANCE_COOKIE = 'These cookies collect information about how you use our website such as which pages you visit regularly. These cookies are used to provide you with a high-quality experience by doing things such as tracking page load speed, site response times, and error messages.'

